export const AVAILABILITY_REPOSITORY = Symbol('AVAILABILITY_REPOSITORY');

export const AVAILABILITY_CHAIN_REPOSITORY = Symbol(
  'AVAILABILITY_CHAIN_REPOSITORY',
);

export const AVAILABILITY_PUBLIC_REPOSITORY = Symbol(
  'AVAILABILITY_PUBLIC_REPOSITORY',
);
