export const AVAILABILITY_REPOSITORY = Symbol('AVAILABILITY_REPOSITORY');

export const AVAILABILITY_CHAIN_REPOSITORY = Symbol(
  'AVAILABILITY_CHAIN_REPOSITORY',
);

export const AVAILABILITY_PUBLIC_REPOSITORY = Symbol(
  'AVAILABILITY_PUBLIC_REPOSITORY',
);

export const AVAILABILITY_SNAPSHOT_REPOSITORY = Symbol(
  'AVAILABILITY_SNAPSHOT_REPOSITORY',
);

export const AVAILABILITY_GENERATOR_SERVICE = Symbol(
  'AVAILABILITY_GENERATOR_SERVICE',
);

export const AVAILABILITY_INDEX_REPOSITORY = Symbol(
  'AVAILABILITY_INDEX_REPOSITORY',
);

export const AVAILABILITY_SERVICES_REPOSITORY = Symbol(
  'AVAILABILITY_SERVICES_REPOSITORY',
);
