import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { BranchProvider } from "@/context/BranchContext";
import { PaymentProvider } from "@/context/PaymentContext";
import Script from "next/script";
import { UIAlertsProvider } from "@/context/UIAlertsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700", "800", "900"], // opcional
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="afterInteractive"
        />
        <UIAlertsProvider>
          <BranchProvider>
          <AuthProvider>
            <PaymentProvider>{children}</PaymentProvider>
          </AuthProvider>
        </BranchProvider>
        </UIAlertsProvider>
      </body>
    </html>
  );
}
