export const BRANCHES_REPOSITORY = Symbol('BRANCHES_REPOSITORY');
export const BRANCH_IMAGES_REPOSITORY = Symbol('BRANCH_IMAGES_REPOSITORY');
export const BRANCH_SETTINGS_REPOSITORY = Symbol('BRANCH_SETTINGS_REPOSITORY');
