export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');

export const STAFF_REPOSITORY = Symbol('STAFF_REPOSITORY');

export const INVITES_REPOSITORY = Symbol('INVITES_REPOSITORY');

export const BRANCHES_REPOSITORY = Symbol('BRANCHES_REPOSITORY');

export const PUBLIC_USERS_REPOSITORY = Symbol('PUBLIC_USERS_REPOSITORY');

export const PUBLIC_SESSIONS_REPOSITORY = Symbol('PUBLIC_SESSIONS_REPOSITORY');

export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');

export const GOOGLE_TOKEN_VERIFIER = Symbol('GOOGLE_TOKEN_VERIFIER');
