// tokens.ts

export const BENEFIT_RULE_REPOSITORY = Symbol('BENEFIT_RULE_REPOSITORY');
export const BENEFIT_POINTS_REPOSITORY = Symbol('BENEFIT_POINTS_REPOSITORY');
export const BENEFIT_PROGRESS_REPOSITORY = Symbol(
  'BENEFIT_PROGRESS_REPOSITORY',
);
export const BENEFIT_PROGRAM_REPOSITORY = Symbol('BENEFIT_PROGRAM_REPOSITORY');
export const BENEFIT_RULE_HANDLERS = Symbol('BENEFIT_RULE_HANDLERS');
export const BENEFIT_REWARD_HANDLERS = Symbol('BENEFIT_REWARD_HANDLERS');
export const BENEFIT_RULE_CONFIG_VALIDATORS = Symbol(
  'BENEFIT_RULE_CONFIG_VALIDATORS',
);

export const BENEFIT_REWARD_REPOSITORY = Symbol('BENEFIT_REWARD_REPOSITORY');
export const BENEFIT_BALANCE_REPOSITORY = Symbol('BENEFIT_BALANCE_REPOSITORY');
export const BENEFIT_REDEMPTION_REPOSITORY = Symbol(
  'BENEFIT_REDEMPTION_REPOSITORY',
);
export const BENEFIT_TRANSACTION_MANAGER = Symbol(
  'BENEFIT_TRANSACTION_MANAGER',
);

export const BENEFIT_TIERS_REPOSITORY = Symbol('BENEFIT_TIERS_REPOSITORY');
// core/ports/tokens.ts

export const TIER_REWARDS_REPOSITORY = Symbol('TIER_REWARDS_REPOSITORY');

// ports/tokens.ts

export const TIER_REWARD_CONFIG_VALIDATORS = Symbol(
  'TIER_REWARD_CONFIG_VALIDATORS',
);
